# Generated by Django 5.2.13 on 2026-04-28 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchChallanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('product_description', models.TextField()),
                ('dispatched_qty', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('serial_numbers', models.TextField(blank=True)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'dispatch_challan_items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DispatchPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('plan_number', models.CharField(max_length=50, unique=True)),
                ('planned_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'dispatch_plans',
                'ordering': ['-planned_date'],
            },
        ),
        migrations.CreateModel(
            name='PodRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('received_by', models.CharField(blank=True, max_length=100)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('signature_path', models.CharField(blank=True, max_length=500)),
                ('pod_photo_path', models.CharField(blank=True, max_length=500)),
                ('condition', models.CharField(blank=True, choices=[('good', 'Good'), ('damaged', 'Damaged'), ('partial', 'Partial')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'pod_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('service_areas', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'transporters',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('vehicle_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=100)),
                ('capacity_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_own', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'vehicles',
                'ordering': ['vehicle_number'],
            },
        ),
        migrations.CreateModel(
            name='DispatchChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('challan_number', models.CharField(max_length=50, unique=True)),
                ('delivery_address_text', models.TextField(blank=True)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('driver_mobile', models.CharField(blank=True, max_length=20)),
                ('lr_number', models.CharField(blank=True, max_length=100)),
                ('dispatch_date', models.DateField(db_index=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('packed', 'Packed'), ('loaded', 'Loaded'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('pod_pending', 'POD Pending'), ('closed', 'Closed'), ('failed', 'Failed')], db_index=True, default='planned', max_length=20)),
                ('freight_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('freight_paid_by', models.CharField(blank=True, choices=[('company', 'Company'), ('customer', 'Customer')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('pdf_path', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_challans', to='customers.customer')),
                ('delivery_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_challans', to='customers.address')),
            ],
            options={
                'db_table': 'dispatch_challans',
                'ordering': ['-dispatch_date'],
            },
        ),
    ]
