# Generated by Django 5.2.13 on 2026-04-28 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('product_description', models.TextField()),
                ('quantity_ordered', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_dispatched', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_pending', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reserved', 'Reserved'), ('ready', 'Ready'), ('dispatched', 'Dispatched'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'sales_order_items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InstallationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('site_address', models.TextField()),
                ('site_contact_name', models.CharField(blank=True, max_length=100)),
                ('site_contact_mobile', models.CharField(blank=True, max_length=20)),
                ('civil_readiness', models.CharField(choices=[('ready', 'Ready'), ('not_ready', 'Not Ready'), ('partial', 'Partial'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('electrical_readiness', models.CharField(choices=[('ready', 'Ready'), ('not_ready', 'Not Ready'), ('partial', 'Partial'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('expected_install_date', models.DateField(blank=True, null=True)),
                ('special_site_requirements', models.TextField(blank=True)),
                ('access_instructions', models.TextField(blank=True)),
                ('permissions_required', models.BooleanField(default=False)),
                ('permission_details', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'installation_requirements',
            },
        ),
        migrations.CreateModel(
            name='MaterialChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('required_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shortage_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('partial', 'Partial'), ('shortage', 'Shortage'), ('procuring', 'Procuring'), ('ready', 'Ready')], db_index=True, default='available', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_checklists', to='inventory.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'material_checklists',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('milestone_name', models.CharField(max_length=255)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('overdue', 'Overdue')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_milestones',
                'ordering': ['target_date'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('ready_to_dispatch', 'Ready to Dispatch'), ('partially_dispatched', 'Partially Dispatched'), ('fully_dispatched', 'Fully Dispatched'), ('installed', 'Installed'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=30)),
                ('order_date', models.DateField(db_index=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_terms', models.TextField(blank=True)),
                ('delivery_terms', models.TextField(blank=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('freight_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_sales_exec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_owned', to=settings.AUTH_USER_MODEL)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_orders', to='customers.address')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_confirmed', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='customers.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='customers.customer')),
            ],
            options={
                'db_table': 'sales_orders',
                'ordering': ['-order_date'],
            },
        ),
    ]
