# Generated by Django 5.2.13 on 2026-04-28 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(db_index=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('performed_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'inquiry_activity_logs',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='InquiryFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('follow_up_type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('visit', 'Visit'), ('whatsapp', 'WhatsApp'), ('meeting', 'Meeting')], max_length=20)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('missed', 'Missed'), ('rescheduled', 'Rescheduled')], db_index=True, default='pending', max_length=20)),
                ('outcome', models.TextField(blank=True)),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inquiry_follow_ups',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='InquiryLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('product_description', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('specification_notes', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'inquiry_line_items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InquirySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'inquiry_sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('inquiry_number', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('mobile', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('project_description', models.TextField(blank=True)),
                ('inquiry_type', models.CharField(choices=[('new_project', 'New Project'), ('spare_parts', 'Spare Parts'), ('amc', 'AMC'), ('service', 'Service'), ('other', 'Other')], db_index=True, max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='medium', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('quoted', 'Quoted'), ('converted', 'Converted'), ('lost', 'Lost'), ('on_hold', 'On Hold')], db_index=True, default='new', max_length=20)),
                ('expected_order_date', models.DateField(blank=True, null=True)),
                ('site_location', models.TextField(blank=True)),
                ('budget_range', models.CharField(blank=True, max_length=100)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('lost_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='customers.customer')),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'db_table': 'inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
