# Generated by Django 5.2.13 on 2026-04-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_quotationactivitylog_quotationcommunicationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='gross_margin_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
